on:
  push:
    branches:
      - dev*

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  discussions: write

jobs:
  pre-release:
    name: Nightly-release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
          cross: true
        - target: aarch64-unknown-linux-musl
          os: ubuntu-latest
          cross: true
        - target: armv7-unknown-linux-musleabi
          os: ubuntu-latest
          cross: true
        - target: x86_64-apple-darwin
          os: macos-latest
          cross: false
        - target: aarch64-apple-darwin
          os: macos-latest
          cross: false
        - target: x86_64-pc-windows-msvc
          os: windows-latest
          cross: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.77.0
        with:
          target: ${{ matrix.target }}        
      - name: Run Cross
        if: ${{ matrix.cross }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross.git --locked --rev 085092ca
          cross build --bin utpm -p utpm --release --target ${{ matrix.target }}

      - name: Set up MinGW on Windows
        uses: egor-tensin/setup-mingw@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          platform: x64

      - name: Set up GCC
        if: ${{ !matrix.cross }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Run Cargo
        if: ${{ !matrix.cross }}
        run: |
          cargo build --bin utpm -p utpm --release --target ${{ matrix.target }}
          
      - name: Create artifact directory
        shell: bash
        run: |
          directory=utpm-${{ matrix.target }}
          mkdir $directory
          cp README.md LICENSE $directory
          if [ -f target/${{ matrix.target }}/release/utpm.exe ]; then
            cp target/${{ matrix.target }}/release/typst.exe $directory
            7z a -r $directory.zip $directory
          else
            cp target/${{ matrix.target }}/release/utpm $directory
            tar cJf $directory.tar.xz $directory
          fi

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6
      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          tag_name: ${{ steps.short-sha.outputs.sha }}
          generate_release_notes: true
          files: |
            utpm-${{ matrix.target }}.*        
